default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fighting_scheduler_development

test:
  <<: *default
  database: fighting_scheduler_test
  
production:
  <<: *default
  database: fighting_scheduler_production
  username: fighting_scheduler
  password: <%= ENV['fighting_scheduler_DATABASE_PASSWORD'] %>